
version: "3"
services:
  emily-face-mask-detector-api-xa5jt2:

    build:
      dockerfile: ./.devcontainer/Dockerfile
    
    command: /bin/sh -c "while sleep 1000; do :; done"

    runtime: ${RUNTIME}
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES}
    ipc: ${IPC}
  
